open module io.micronaut.core {
	requires transitive org.slf4j;

	exports io.micronaut.core.annotation;
	exports io.micronaut.core.attr;
	exports io.micronaut.core.beans;
	exports io.micronaut.core.beans.exceptions;
	exports io.micronaut.core.bind;
	exports io.micronaut.core.bind.annotation;
	exports io.micronaut.core.bind.exceptions;
	exports io.micronaut.core.cli;
	exports io.micronaut.core.cli.exceptions;
	exports io.micronaut.core.convert;
	exports io.micronaut.core.convert.converters;
	exports io.micronaut.core.convert.exceptions;
	exports io.micronaut.core.convert.format;
	exports io.micronaut.core.convert.value;
	exports io.micronaut.core.exceptions;
	exports io.micronaut.core.graal;
	exports io.micronaut.core.io;
	exports io.micronaut.core.io.buffer;
	exports io.micronaut.core.io.file;
	exports io.micronaut.core.io.scan;
	exports io.micronaut.core.io.service;
	exports io.micronaut.core.io.socket;
	exports io.micronaut.core.naming;
	exports io.micronaut.core.naming.conventions;
	exports io.micronaut.core.optim;
	exports io.micronaut.core.order;
	exports io.micronaut.core.reflect;
	exports io.micronaut.core.reflect.exception;
	exports io.micronaut.core.serialize;
	exports io.micronaut.core.serialize.exceptions;
	exports io.micronaut.core.type;
	exports io.micronaut.core.util;
	exports io.micronaut.core.util.clhm;
	exports io.micronaut.core.util.functional;
	exports io.micronaut.core.util.locale;
	exports io.micronaut.core.value;
	exports io.micronaut.core.version;
	exports io.micronaut.core.version.annotation;
	exports io.micronaut.asm.commons;
	exports io.micronaut.asm.tree.analysis;
	exports io.micronaut.asm.tree;
	exports io.micronaut.asm;
	exports io.micronaut.asm.signature;
	exports io.micronaut.caffeine;
	exports io.micronaut.caffeine.base;
	exports io.micronaut.caffeine.cache;
	exports io.micronaut.caffeine.cache.stats;

	uses io.micronaut.core.type.TypeInformationProvider;
	uses io.micronaut.core.optim.StaticOptimizations.Loader;
}